[project]
name = "peony"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Patchethium", email = "asguftuikh@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
